webapp/admin/views.py
from flask import Blueprint, render_template

from webapp.user.decorators import admin_required
from webapp.user.models import User
from webapp.boards.models import Boards

blueprint = Blueprint("admin", __name__, url_prefix="/admin")

@blueprint.route("/")
@admin_required
def admin_index():
    title = "Админка"
    users = User.query.all()
    users_boards = {}
    for user in users:
        boards_list = Boards.query.filter_by(user_id=user.id).all()
        users_boards[user.id] = len(boards_list)
    return render_template(
        "admin/index.html", page_title=title,
        users=users, users_boards=users_boards)

webapp/user/views.py
from flask import Blueprint, flash, redirect, render_template, url_for
from flask_login import current_user, login_user, logout_user

from webapp.db import db
from webapp.user.forms import LoginForm, RegistrationForm
from webapp.user.models import User

blueprint = Blueprint("user", __name__, url_prefix="/users")

@blueprint.route("/login")
def login():
    if current_user.is_authenticated:
        return redirect(url_for("home.index"))
    title = "Авторизация"
    login_form = LoginForm()
    return render_template("user/login.html", page_title=title, form=login_form)

@blueprint.route("/process-login", methods=["POST"])
def process_login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter(User.username == form.username.data).first()
        if user and user.check_password(form.password.data):
            login_user(user, remember=form.remember_me.data)
            flash("Вы успешно вошли на сайт")
            return redirect(url_for("home.index"))
    flash("Неправильное имя или пароль")
    return redirect(url_for("user.login"))

@blueprint.route("/logout")
def logout():
    logout_user()
    flash("Вы успешно разлогинились")
    return redirect(url_for("home.index"))

@blueprint.route("/register")
def register():
    if current_user.is_authenticated:
        return redirect(url_for("home.index"))
    title = "Регистрация"
    form = RegistrationForm()
    return render_template("user/registration.html", page_title=title, form=form)

@blueprint.route("/process-reg", methods=["Post"])
def process_reg():
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(username=form.username.data, email=form.email.data, role = "user")
        user.set_password(form.password.data)
        db.session.add(user)
        db.session.commit()
        flash("Вы успешно зарегистрировались!")
        return redirect(url_for("user.login"))
    else:
        for field, errors in form.errors.items():
            for error in errors:
                flash("Ошибка в поле {}: {}".format(
                    getattr(form, field).label.text,
                    error
                ))
        return redirect(url_for('user.register'))

webapp/templates/base.html
<!doctype html>
<html lang="ru">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type= "text/css" href="{{ url_for('static', filename='styles/styles.css') }}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>{{ page_title }}</title>
  </head>
  <body>
  <div class="block">
    {% include "menu.html" %}
    <div class="container">
        <h1 style="color: #e6cfc8; text-shadow: 2px 2px 3px #473931; font-size: 50px; font-weight: bold;">{{ page_title }}</h1>
        {% block content %}{% endblock %}
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </div>
  </body>
</html>

webapp/templates/menu.html
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e6cfc8">
  <a class="navbar-brand">Shelves</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Домашняя страница</a>
      </li>
    </ul>
    <ul class="navbar-nav">
      {% if current_user.is_authenticated %}
      <li class="nav-item">
          <a class="nav-link" href="{{ url_for('boards.create_board') }}">Создать доску</a>
      </li>
      {% endif %}
    </ul>
    <ul class="navbar-nav">
      {% if current_user.is_authenticated %}
        <li class="nav-item">
          <span class="nav-link">Привет, {{ current_user.username }}!</span>
        </li>
        {% if current_user.is_admin %}
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('admin.admin_index') }}">Админка</a>
        </li>
        {% endif %}
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('user.logout') }}">Выйти</a>
        </li>
      {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('user.register') }}">Регистрация</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('user.login') }}">Войти</a>
        </li>
      {% endif %}
      </li>
    </ul>
  </div>
</nav>