webapp/boards/models.py
from webapp.db import db
from sqlalchemy import ForeignKey
from sqlalchemy.orm import relationship

class Boards(db.Model):
    __tablename__ = "boards"
    id = db.Column(db.Integer, primary_key=True)
    board_name = db.Column(db.String(100), nullable=False)
    user_id = db.Column(db.Integer, ForeignKey("user.id"))
    user = relationship("User", back_populates="boards")
    col = relationship("Col", back_populates="boards")

    def __repr__(self):
        return "<Boards {}>".format(self.board_name)

webapp/boards/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, ValidationError
from flask_login import current_user

from webapp.boards.models import Boards

class CreateBoard(FlaskForm):
    board_name = StringField("Название доски", validators=[DataRequired()], render_kw={"class": "form-control"})
    submit = SubmitField("Создать", render_kw={"class": "btn btn-dark-brown"})

    def validate_board_name(self, board_name):
        name_count = 0
        boards = Boards.query.filter_by(user_id=current_user.id).all()
        for board in boards:
            if board.board_name == board_name.data:
                name_count += 1
        if name_count > 0:
            raise ValidationError("Доска с таким именем уже существует!")

webapp/boards/views.py
from flask import Blueprint, flash, redirect, render_template, url_for
from flask_login import current_user


from webapp.db import db
from webapp.boards.forms import CreateBoard
from webapp.boards.models import Boards
from webapp.cards.models import Cards
from webapp.col.models import Col

blueprint = Blueprint("boards", __name__, url_prefix="/boards")

@blueprint.route("/<int:id>", methods=["GET"])
def get_board(id):
    board = Boards.query.filter_by(id=id).first()
    title = board.board_name
    cols = Col.query.filter_by(board_id=id).order_by(Col.number).all()
    cards_list = []
    col_len = {}
    col_short_name = {}
    for col in cols:
        cards = Cards.query.filter_by(col_id=col.id).order_by(Cards.number).all()
        col_len[col.id] = len(cards)
        name = col.col_name
        if len(name) <= 21:
            col_short_name[col.id] = name
        else:
            col_short_name[col.id] = name[:18] + "..."
        for card in cards:
            cards_list.append(card)
    return render_template(
        "boards/board.html", page_title=title,
        board_id=id, cards_list=cards_list, col_list=cols, col_len=col_len, col_short_name=col_short_name
    )

@blueprint.route("/create-board")
def create_board():
    if not current_user.is_authenticated:
        return redirect(url_for("user.login"))
    form = CreateBoard()
    title = "Создание новой доски"
    return render_template("boards/create_board.html", page_title=title, form=form)

@blueprint.route("/process-create-board", methods=["Post"])
def process_create_board():
    form = CreateBoard()
    if form.validate_on_submit():
        board = Boards(board_name=form.board_name.data, user_id=current_user.id)
        db.session.add(board)
        db.session.commit()
        col1 = Col(col_name="1", number=1, board_id=board.id)
        col2 = Col(col_name="2", number=2, board_id=board.id)
        col3 = Col(col_name="3", number=3, board_id=board.id)
        db.session.add(col1)
        db.session.add(col2)
        db.session.add(col3)
        db.session.commit()
        flash("Доска успешно создана")
        return redirect(url_for("home.index"))
    else:
        for field, errors in form.errors.items():
            for error in errors:
                flash("{}".format(error))
    return redirect(url_for("boards.create_board"))

@blueprint.route("/del-board/<int:board_id>/<origin>", methods=["GET"])
def del_board(board_id, origin):
    board = Boards.query.filter_by(id=board_id).first()
    return render_template("boards/delete_board.html", page_title="Удаление доски",
                           board=board, origin=origin)

@blueprint.route("/process-del-board/<int:board_id>", methods=["POST"])
def process_del_board(board_id):
    board = db.session.query(Boards).get(board_id)
    col_list = Col.query.filter_by(board_id=board_id)
    for col in col_list:
        cards_list = Cards.query.filter_by(col_id=col.id).all()
        for card in cards_list:
            db.session.delete(card)
        db.session.delete(col)
    db.session.delete(board)
    db.session.commit()
    flash("Доска удалена")
    return redirect(url_for("home.index"))

webapp/cards/views.py
from flask import Blueprint, flash, redirect, render_template, url_for, request
from flask_login import current_user

from webapp.db import db

from webapp.cards.forms import CreateCard, EditCard
from webapp.cards.models import Cards
from webapp.col.models import Col

blueprint = Blueprint("cards", __name__, url_prefix="/cards")

@blueprint.route("/create-card/<int:board_id>//<int:col_id>", methods=["GET"])
def create_card(board_id, col_id):
    if not current_user.is_authenticated:
        return redirect(url_for("user.login"))
    form = CreateCard()
    title = "Создание карточки"
    return render_template(
        "cards/create_card.html", page_title=title,
        form=form, col_id=col_id, board_id=board_id)

@blueprint.route("/process-create-card", methods=["Post"])
def process_create_card():
    form = CreateCard()
    if form.validate_on_submit():
        col_id = request.form['col']
        board_id = request.form['board']
        all_cards = Cards.query.filter_by(col_id=col_id).all()
        number = len(all_cards) + 1
        card = Cards(text=form.text.data, number=number, col_id=col_id)
        db.session.add(card)
        db.session.commit()
        return redirect(url_for("boards.get_board", id=board_id))
    else:
        for field, errors in form.errors.items():
            for error in errors:
                flash("{}".format(error))
    return redirect(url_for("cards.create_card"))

@blueprint.route("/edit-card/<int:board_id>/<int:card_id>", methods=["GET"])
def edit_card(board_id, card_id):
    if not current_user.is_authenticated:
        return redirect(url_for("user.login"))
    form = EditCard()
    title = "Редактирование карточки"
    card = Cards.query.get(card_id)
    return render_template(
        "cards/edit_card.html", page_title=title,
        form=form, card=card, board_id=board_id)

@blueprint.route("/process-edit-card", methods=["Post"])
def process_edit_card():
    form = EditCard()
    if form.validate_on_submit():
        card_id = request.form['card']
        card = db.session.query(Cards).get(card_id)
        card.text = form.text.data
        db.session.commit()
        board_id = request.form['board']
        return redirect(url_for("boards.get_board", id=board_id))
    else:
        for field, errors in form.errors.items():
            for error in errors:
                flash("{}".format(error))
    return redirect(url_for("cards.edit_card"))

def get_prev_id(cards_list, searched_number):
    for card in cards_list:
        if card.number == searched_number:
            prev_id = card.id
            return prev_id

def change_number(prev_id, card_number, card, new_card_number):
    prev_card = db.session.query(Cards).get(prev_id)
    if prev_card:
        prev_card.number = card_number
        card.number = new_card_number
        db.session.commit()

def number_plus(cards_list, card_number):
    for c in cards_list:
        if c.number < card_number:
            prev_card = db.session.query(Cards).get(c.id)
            if prev_card:
                prev_card.number += 1

def number_minus(cards_list, card_number):
    for c in cards_list:
        if c.number > card_number:
            prev_card = db.session.query(Cards).get(c.id)
            if prev_card:
                prev_card.number -= 1

@blueprint.route("/move-card/<int:board_id>/<int:card_id>/<int:act>", methods=["GET"])
def move_card(board_id, card_id, act):
    card = db.session.query(Cards).get(card_id)
    card_number = card.number
    col_id = card.col_id
    cards_list = Cards.query.filter_by(col_id=col_id).all()
    if act == 1:
        number_plus(cards_list, card_number)
        card.number = 1
        db.session.commit()
    elif act == 2:
        new_card_number = card_number - 1
        prev_id = get_prev_id(cards_list, new_card_number)
        change_number(prev_id, card_number, card, new_card_number)
    elif act == 3:
        new_card_number = card_number + 1
        prev_id = get_prev_id(cards_list, new_card_number)
        change_number(prev_id, card_number, card, new_card_number)
    else:
        number_minus(cards_list, card_number)
        card.number = len(cards_list)
        db.session.commit()
    return redirect(url_for("boards.get_board", id=board_id))

@blueprint.route("/del-card/<int:board_id>/<int:card_id>", methods=["GET"])
def del_card(board_id, card_id):
    card = db.session.query(Cards).get(card_id)
    cards_list = Cards.query.filter_by(col_id=card.col_id).all()
    card_number = card.number
    db.session.delete(card)
    number_minus(cards_list, card_number)
    db.session.commit()
    return redirect(url_for("boards.get_board", id=board_id))

webapp/col/views.py
from flask import Blueprint, flash, redirect, render_template, url_for, request
from flask_login import current_user

from webapp.db import db

from webapp.col.forms import EditColName
from webapp.cards.models import Cards
from webapp.col.models import Col
from webapp.cards.views import number_minus

blueprint = Blueprint("col", __name__, url_prefix="/col")

@blueprint.route("/edit-col-name/<int:board_id>/<int:col_id>", methods=["GET"])
def edit_col_name(board_id, col_id):
    if not current_user.is_authenticated:
        return redirect(url_for("user.login"))
    form = EditColName()
    title = "Изменить название колонки"
    col = Col.query.get(col_id)
    return render_template(
        "col/edit_col_name.html", page_title=title, form=form,
        col=col, board_id=board_id)

@blueprint.route("/process-edit-col-name", methods=["Post"])
def process_edit_col_name():
    form = EditColName()
    if form.validate_on_submit():
        col_id = request.form['col']
        col = db.session.query(Col).get(col_id)
        col.col_name = form.name.data
        db.session.commit()
        board_id = request.form['board']
        return redirect(url_for("boards.get_board", id=board_id))
    else:
        for field, errors in form.errors.items():
            for error in errors:
                flash("{}".format(error))
    return redirect(url_for("cards.edit_card"))

@blueprint.route("/move-to-col/<int:board_id>/<int:col_id>/<int:card_id>/", methods=["GET"])
def move_to_col(board_id, col_id, card_id):
    card = db.session.query(Cards).get(card_id)
    prev_col_id = card.col_id
    prev_card_num = card.number
    card.col_id = col_id
    new_cards_list = Cards.query.filter_by(col_id=col_id).all()
    card.number = len(new_cards_list)
    prev_cards_list = Cards.query.filter_by(col_id=prev_col_id).all()
    number_minus(prev_cards_list, prev_card_num)
    db.session.commit()
    return redirect(url_for("boards.get_board", id=board_id))

webapp/templates/boards/board.html
{% extends "base.html" %}

{% block content %}
<div class="row">
    <br>
</div>
    <div class="d-flex justify-content-between">
        <div class="p-2">
            <form action="{{ url_for('cards.create_card', board_id=board_id, col_id=col_list[0].id) }}" method="GET">
                <input type="submit" class="btn btn-dark-brown" value="Создать карточку">
            </form>
        </div>
        <div class="p-2">
            <form action="{{ url_for('boards.del_board', board_id=board_id, origin='board') }}" method="GET">
                <input type="submit" class="btn btn-dark-brown" value="Удалить доску">
            </form>
        </div>
    </div>
<div class="row">
    <br>
</div>
<div class="row" style="font-size: 20px;">
    {% for col in col_list %}
    <div class="col-4">
        <div class="menu-bar">
        <ul class="list-group">
            <li class="list-group-item" style="background-color: #c29f93; color: #291f1b">
                <h3>{{ col.col_name }}</h3>
                <ul class="list-group">
                    <li>
                        <form action="{{ url_for('cards.create_card', board_id=board_id, col_id=col.id) }}" method="GET">
                            <input type="submit" class="btn btn-dark-brown" style="width: 203px" value="Создать карточку">
                        </form>
                    </li>
                    <li>
                        <form action="{{ url_for('col.edit_col_name', board_id=board_id, col_id=col.id) }}" method="GET">
                            <input type="submit" class="btn btn-dark-brown" style="width: 203px" value="Редактировать название">
                        </form>
                    </li>
                </ul>
            </li>
        </ul>
        {% for card in cards_list %}
            {% if card.col_id == col.id %}
            <ul class="list-group">
              <li class="list-group-item card">{{ card.text }}
                    <ul class="list-group">
                        <li>
                            <form action="{{ url_for('cards.edit_card', board_id=board_id, card_id=card.id) }}" method="GET">
                                <input type="submit" class="btn btn-dark-brown" style="width: 203px" value="Редактировать карточку">
                            </form>
                        </li>

                        {% if card.number > 1 %}
                        <li class="d-flex flex-row">
                            <form action="{{ url_for('cards.move_card', board_id=board_id, card_id=card.id, act=1) }}" method="GET">
                                <input type="submit" class="btn btn-dark-brown btn-lg" style="width: 101.5px" value="&UpArrowBar;">
                            </form>
                            <form action="{{ url_for('cards.move_card', board_id=board_id, card_id=card.id, act=2) }}" method="GET">
                                <input type="submit" class="btn btn-dark-brown btn-lg" style="min-width: 101.5px" value="&UpArrow;">
                            </form>
                        </li>
                        {% endif %}
                        {% if card.number != col_len[col.id] %}
                        <li class="d-flex flex-row">
                            <form action="{{ url_for('cards.move_card', board_id=board_id, card_id=card.id, act=3) }}" method="GET">
                                <input type="submit" class="btn btn-dark-brown btn-lg" style="min-width: 101.5px" value="&downarrow;">
                            </form>
                            <form action="{{ url_for('cards.move_card', board_id=board_id, card_id=card.id, act=4) }}" method="GET">
                                <input type="submit" class="btn btn-dark-brown btn-lg" style="min-width: 101.5px" value="&DownArrowBar;">
                            </form>
                        </li>
                        {% endif %}

                            {% for col in col_list %}
                                {% if col.id != card.col_id %}
                            <li>
                                <form action="{{ url_for('col.move_to_col', board_id=board_id, card_id=card.id, col_id = col.id) }}" method="GET">
                                    <input type="submit" class="btn btn-dark-brown" style="width: 203px; white-space: normal;" value="Переместить в колонку {{ col_short_name[col.id] }}">
                                </form>
                            </li>
                                {% endif %}
                            {% endfor %}
                        <li>
                            <form action="{{ url_for('cards.del_card', board_id=board_id, card_id=card.id) }}" method="GET">
                                <input type="submit" class="btn btn-dark-brown" style="width: 203px" value="Удалить карточку">
                            </form>
                        </li>
                    </ul>
              </li>
            </ul>
            {% endif %}
        {% endfor %}
        </div>
    </div>
    {% endfor %}
</div>
<div class="row" style="line-height: 170px">
    <br>
</div>
{% endblock %}

webapp/templates/boards/create_board.html
{% extends "base.html" %}

{% block content %}
{% with messages = get_flashed_messages() %}
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-light" role="alert">
            {{ message }}<br>
        </div>
        {% endfor %}
    {% endif %}
{% endwith %}
    <div class="row">
        <div class="col-4 container header">

            <form action="{{ url_for('boards.process_create_board') }}" method="POST">
                {{ form.hidden_tag() }}
                <div class="form-group">
                    {{ form.board_name.label }}
                    {{ form.board_name() }}
                </div>
                {{ form.submit() }}
            </form>

        </div>
    </div>
{% endblock %}

webapp/templates/boards/delete_board.html
{% extends "base.html" %}

{% block content %}
<div class="row">
    <div class="col-8 container header">
        <h2>Вы действительно хотите удалить доску "{{ board.board_name }}"?</h2>
        <div class="d-flex flex-row mb-3 justify-content-center">
            <div class="p-2">
                <form action="{{ url_for('boards.process_del_board', board_id=board.id) }}" method="POST">
                    <input type="submit" class="btn btn-dark-brown" style="min-width: 50px" value="Да">
                </form>
            </div>
            <div class="p-2">
                {% if origin=='home' %}
                <form action="{{ url_for('home.index') }}" method="GET">
                    <input type="submit" class="btn btn-dark-brown" value="Нет">
                </form>
                {% elif origin=='board' %}
                <form action="{{ url_for('boards.get_board', id=board.id) }}" method="GET">
                    <input type="submit" class="btn btn-dark-brown" value="Нет">
                </form>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}